In [35]:
import pandas as pd

DATA = pd.read_csv('outputs\\AMIcsv\\EN2001a.count.csv', delimiter=',') # , names=['start', 'end', 'duration', 'count']

In [39]:
args = {'useVAD': True, 'path': 'F:\\' }


def func(useVAD, path):
    print(useVAD, path)

func(**args)

True F:\


In [40]:
args_1 = {
    'useVAD': True,
    'path': 'F:\\'
}

func(**args_1)

True F:\


In [11]:
from utils_2 import ananas

print(ananas)

[4, 5, 6]


In [9]:
import os
import pandas as pd

files = os.listdir('data\\AMI\\Count')
    
#DATA = pd.read_csv('data\\AMI\\Count\\' + files[0], delimiter=',')

DATA = pd.DataFrame({'start': [], 'duration': [], 'count': []})



In [12]:
DATA

,start,duration,count
0,0.00,3.34,0.0
1,3.34,0.54,1.0
2,3.88,1.69,0.0
3,5.57,0.03,1.0
4,5.60,0.34,2.0
...,...,...,...
1411,2307.65,0.39,0.0
1412,2308.04,0.21,1.0
1413,2308.25,15.65,0.0
1414,2323.90,0.49,1.0


In [11]:


for f in files:
    file_csv = 'data\\AMI\\Count\\' + f # путь к файлам

    data = pd.read_csv(file_csv, delimiter=',') # колонки - start, duration, count или (start, end, duration, count)
    
    #DATA.join(data)
    DATA = pd.concat([DATA, data])

In [54]:
DATA[(DATA.count == 1) & (DATA.duration > 0.1)]

,start,duration,count


In [13]:
duration = [[], [], [], [], []]

data = DATA.values

for st, dur, cnt in data:
    duration[int(cnt)].append(dur)

In [14]:
import numpy as numpy

for i in range(len(duration)):
    print('Класс:', i)
    print('Общая длительность', np.sum(duration[i]))
    print('Средняя длительность', np.mean(duration[i]))
    print('Минимальная длительность', np.min(duration[i]))
    print('Максимальная длительность', np.max(duration[i]))
    print('Медианная длительность', np.median(duration[i]))
    
    print('\n')

Класс: 0
Общая длительность 66028.193875
Средняя длительность 1.9296897412105094
Минимальная длительность 0.0099999999997635
Максимальная длительность 815.428625
Медианная длительность 1.0199999999999818


Класс: 1
Общая длительность 250841.88900000005
Средняя длительность 3.3389935307820306
Минимальная длительность 0.0099999999993087
Максимальная длительность 84.6400000000001
Медианная длительность 1.7000000000000457


Класс: 2
Общая длительность 35340.98599999996
Средняя длительность 0.7393047716670493
Минимальная длительность 0.0099999999997635
Максимальная длительность 11.849999999999907
Медианная длительность 0.4600000000000364


Класс: 3
Общая длительность 3790.013999999993
Средняя длительность 0.5237719734660023
Минимальная длительность 0.0099999999997635
Максимальная длительность 14.340000000000032
Медианная длительность 0.3399999999996907


Класс: 4
Общая длительность 196.73000000000212
Средняя длительность 0.4575116279069817
Минимальная длительность 0.0099999999997635
Максима

In [74]:
duration_1 = [[], [], [], [], []]

data = DATA.values

for st, dur, cnt in data:
    duration_1[int(cnt)].append([st, dur, int(cnt)])

In [78]:
duration_1[4]

In [94]:
dur_4 = pd.DataFrame(duration_1[4])

dur_4 = dur_4.sort_values(by=1, ascending=False)


In [95]:
dur_4 = dur_4.values
print(dur_4)

for d in dur_4:
    print(d)

[[6.96900e+02 5.12000e+00 4.00000e+00]
 [9.00440e+02 4.09000e+00 4.00000e+00]
 [2.50120e+02 3.21000e+00 4.00000e+00]
 ...
 [1.57299e+03 1.00000e-02 4.00000e+00]
 [1.41247e+03 1.00000e-02 4.00000e+00]
 [2.18261e+03 1.00000e-02 4.00000e+00]]
[696.9    5.12   4.  ]
[900.44   4.09   4.  ]
[250.12   3.21   4.  ]
[1362.75    3.18    4.  ]
[1113.53    2.87    4.  ]
[191.15   2.76   4.  ]
[2.78682e+03 2.62000e+00 4.00000e+00]
[1855.9     2.59    4.  ]
[1364.86    2.51    4.  ]
[335.9    2.31   4.  ]
[2.96965e+03 2.27000e+00 4.00000e+00]
[1372.83    2.07    4.  ]
[731.07   1.97   4.  ]
[945.97   1.74   4.  ]
[142.83   1.74   4.  ]
[236.88   1.67   4.  ]
[1251.15    1.62    4.  ]
[1105.65    1.6     4.  ]
[1.74511e+03 1.58000e+00 4.00000e+00]
[391.6    1.43   4.  ]
[1.48125e+03 1.41000e+00 4.00000e+00]
[1.56154e+03 1.40000e+00 4.00000e+00]
[928.23   1.4    4.  ]
[1.40473e+03 1.38000e+00 4.00000e+00]
[1.54186e+03 1.34000e+00 4.00000e+00]
[947.95   1.3    4.  ]
[2.20533e+03 1.28000e+00 4.00000e+00

In [92]:
dur_4

,0,1,2
36,696.90,5.12,4
142,900.44,4.09,4
30,250.12,3.21,4
41,1362.75,3.18,4
375,1113.53,2.87,4
...,...,...,...
79,571.73,0.01,4
247,1391.91,0.01,4
415,1572.99,0.01,4
44,1412.47,0.01,4


In [2]:
#duration_1[1][1:][:]

In [1]:
for i in range(4, -1, -1):
    print(i)

4
3
2
1
0


In [99]:
import os
import pandas as pd

files = os.listdir('data\\AMI\\Count')
    
#DATA = pd.read_csv('data\\AMI\\Count\\' + files[0], delimiter=',')

DATA = pd.DataFrame({'start': [], 'duration': [], 'count': []})

In [100]:
for f in files[2:3]:
    file_csv = 'data\\AMI\\Count\\' + f # путь к файлам

    data = pd.read_csv(file_csv, delimiter=',') # колонки - start, duration, count или (start, end, duration, count)
    
    #DATA.join(data)
    DATA = pd.concat([DATA, data])

In [101]:
DATA

,start,duration,count
0,0.00,20.840000,0.0
1,20.84,0.490000,1.0
2,21.33,15.970000,0.0
3,37.30,0.570000,1.0
4,37.87,9.120000,0.0
...,...,...,...
1280,3351.71,3.690000,0.0
1281,3355.40,6.630000,1.0
1282,3362.03,1.410000,0.0
1283,3363.44,2.960000,1.0


In [102]:
count = DATA.values    

duration = [[], [], [], [], []]

for st, dur, cnt in count:
    duration[int(cnt)].append([st, dur, int(cnt)])

In [15]:
#duration

In [104]:
count_1 = []

for i in range(4, -1, -1):

    dur = pd.DataFrame(duration[i])
    if len(dur) > 0: dur = dur.sort_values(by=1, ascending=False) # сортировка по 
    dur = dur.values

    np.random.shuffle(dur)  # перемешивание массива  

    len_cnt = 0
    if i == 4:
        len_max = 0
    for st, d, pers in dur:
        if d > 0.2 and (len_cnt < len_max or i == 4):
            count_1.append([st, d, int(pers)])
            len_cnt += d
            if i == 4:
                len_max += d

count_2 = pd.DataFrame(count_1)
if len(count_2) > 0: count_2 = count_2.sort_values(by=0)
count_2 = count_2.values
if len(count_2) == 0: count_2 = [0, 0, 0]

In [103]:
for i in range(4, -1, -1):

    dur = pd.DataFrame(duration[i])
    print(len(dur))

5
29
330
613
308


In [67]:
if len(count_2) == 0: count_2 = [0, 0, 0]

In [119]:
count_3 = np.array([[0, 0, 0]])

In [120]:
print(count_3)

[[0 0 0]]


In [116]:
count_2

array([[3.47560e+02, 5.00000e-01, 0.00000e+00],
       [1.12945e+03, 4.80000e-01, 4.00000e+00],
       [1.24701e+03, 1.77000e+00, 3.00000e+00],
       [1.71485e+03, 1.36000e+00, 1.00000e+00],
       [1.77098e+03, 2.40000e-01, 4.00000e+00],
       [2.29741e+03, 7.90000e-01, 0.00000e+00],
       [2.77336e+03, 3.90000e-01, 2.00000e+00],
       [3.24273e+03, 3.40000e-01, 2.00000e+00]])

In [125]:
import numpy as np

INTER = pd.DataFrame(count_2, columns=['start', 'duration', 'count'])
#INTER.to_csv('outputs\\Ideal\\AMIcsv_new\\' + file_au + '.count.csv', index=False)

In [126]:
INTER

,start,duration,count
0,347.56,0.50,0.0
1,1129.45,0.48,4.0
2,1247.01,1.77,3.0
3,1714.85,1.36,1.0
4,1770.98,0.24,4.0
5,2297.41,0.79,0.0
6,2773.36,0.39,2.0
7,3242.73,0.34,2.0


In [5]:
import numpy as np
import pickle
import os.path
import xml.etree.ElementTree as ET 
import re
import pandas as pd


#path = 'outputs\\AMIwords\\'
path = 'outputs\\AMIsegments\\'

fnames_cur = os.listdir(path)
print('Количество файлов в папке:', len(fnames_cur))


path_f = []
files_audio = []
for d, dirs, files in os.walk('F:\\amicorpus_1'): # путь к файлам
    for f in files:
        path_1 = os.path.join(d,f) # формирование адреса
        #if f.split('.')[0] != 'ES2002d':
        path_f.append(path_1) # добавление адреса в список
        files_audio.append(f.split('.')[0])

files_audio = list(set(files_audio))

length = {}
a = 2
        
######## Подготовка csv для каждого аудио
for file_au in files_audio[:1]:

    print(file_au)

    files = []
    for name in fnames_cur:
        if file_au in name:
            files.append(name)

    data = []
    for file in files:

        tree = ET.parse(path + file)
        root = tree.getroot()

        person = file.split('.')[1]

        #for dt in root.findall('w'):
        for dt in root.findall('segment'):
            #if dt.get('punc') is None and dt.get('starttime') is not None:
            #    if data != [] and data[-1][1] == float(dt.get('starttime')):
            #        data[-1][1] = float(dt.get('endtime'))
            #    else:    
            data.append([float(dt.get('transcriber_start')), float(dt.get('transcriber_end')), person])

    #print(data)

Количество файлов в папке: 687
EN2006a


In [6]:
data_sort = sorted(data, key=lambda x: x[0])
DATA = pd.DataFrame(data_sort, columns=['start', 'end', 'person'])

In [15]:
DATA

,start,duration,count
0,0.00,3.34,0.0
1,3.34,0.54,1.0
2,3.88,1.69,0.0
3,5.57,0.03,1.0
4,5.60,0.34,2.0
...,...,...,...
1411,2307.65,0.39,0.0
1412,2308.04,0.21,1.0
1413,2308.25,15.65,0.0
1414,2323.90,0.49,1.0


In [16]:

with np.load(os.path.join("models", 'scaler.npz')) as data:
    print(data['arr_0'].shape) #mean
    print(data['arr_1'].shape) #scale

(201,)
(201,)


In [31]:
import pickle 

name = 'EN2002b'

with open('outputs\model_0-4_1sec_stft\AMI_array1-01_amp4mean\pkl\\' + name + '.output_probs.pickle', 'rb') as f:
    pr_labels = pickle.load(f)

with open('outputs\model_0-4_1sec_stft\AMI_array1-01_amp4mean\pkl\\' + name + '.output.pickle', 'rb') as f:
    pr_labels_1 = pickle.load(f)

In [32]:
pr_labels = np.asarray(pr_labels)
pr_labels = np.argmax(pr_labels, axis=1)

In [37]:
print(pr_labels_1[0])

1


In [35]:
print(pr_labels)

[1 0 0 ... 1 4 3]


In [40]:
ggg = [[0, 3, 4], [1, 3, 4]]

for i, g, g1, g2 in enumerate(ggg):
    print(g)

ValueError: not enough values to unpack (expected 4, got 2)

In [14]:
import yaml

with open(r'yaml/train.yaml') as f:
    templates = yaml.load(f, Loader=yaml.FullLoader)

print(templates['batch_size'])

100


In [2]:
yaml.__version__

'5.3.1'